import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/Hero";
import { Datas } from "../public/data";

interface props {
  fetchedDatas: any;
}

const Home: NextPage<props> = (props) => {
  return (
    <div>
      <Head>
        <title>Next-Typescript-Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <div>
        <Hero datas={props.fetchedDatas} />

        <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossOrigin="anonymous"
        ></script>
      </div>
    </div>
  );
};

export async function getStaticProps() {
  //fetch data
  return {
    props: {
      fetchedDatas: Datas,
    },
    revalidate: 1,
  };
}
export default Home;
